version: "3"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=dev
      - PORT=8080
      - API_KEY=someAPIKey,otherAPIKey,oneMoreAPIKey # added support for multiple keys
      - MONGO_URI=mongodb://mongo:27017/app
      - SEARCH_QUERY=songs # search query
      - USE_MOCK=false
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
