version: "3"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=dev
      - PORT=8080
      - API_KEY=googleAPIKey
      - MONGO_URI=mongodb://mongo:27017/app
      - REDIS_URI=redis://redis:6379
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - 27017:27017
  redis:
    image: redis
    ports:
      - 6379:6379
